---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vectorit/public_html
    - /bin/cp -f index.html work.html international.html leadership.html fbr.html services.html about.html contact.html 404.html google547811663ccac796.html robots.txt sitemap.xml .htaccess contact-submit.php inquiries.php t.php $DEPLOYPATH/
    - /bin/cp -Rf css js assets brand $DEPLOYPATH/
    - /bin/mkdir -p $DEPLOYPATH/demo
    - /bin/cp -Rf demo/. $DEPLOYPATH/demo/
